namespace: dev

# API
apiName: pedidos-api
apiImage: 
  name: brunapisera/pedidos-api
  tag: latest
apiNodePort: 30200

# DB
dbName: pedidos_db
# Config map
configmap:
  name: pedidos-config-map
  data:
    DB_HOST: 
    DB_PORT: 5432
    DB_USER: postgres
    DB_NAME: pedidos_db

# Secret
secret:
  name: secret

rabbitmq:
  username: xtpbliuz 
  hostname: woodpecker.rmq.cloudamqp.com
  password: 
  port: 5672
  virtualhost: xtpbliuz