namespace: default

# API
apiName: pedidos-api
apiImage: 
  name: brunapisera/pedidos-api
  tag: latest
apiNodePort: 30200

# DB
dbName: pedidos-db
# Config map
configmap:
  name: pedidos-config-map
  data:
    DB_HOST: svc-pedidos-db
    DB_PORT: 5432
    DB_USER: postgres
    DB_NAME: pedidosdb

# Secret
secret:
  name: secret